### ISSUE TITLE
can't install the demo apk

### ISSUE THREAD

**Issue by ysnows** [nikhilpanju/FabFilter#1]
error: 
```adb: failed to install /Users/ysnows/Desktop/FabFilter.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]```

**Comment by Qamar4P** [comment]
@ysnows This is debug apk. Use -t i.e. `adb install -r -t FabFilter.apk`. Work for me

**Comment by nikhilpanju** [comment]
You can get the app from the Play Store directly. Readme will be updated soon.
https://play.google.com/store/apps/details?id=com.nikhilpanju.fabfilter
