### ISSUE TITLE
bindView is unresolved

### ISSUE THREAD

**Issue by pcsaunak** [nikhilpanju/FabFilter#3]
I wanted a way to comment but i am creating a issue here, I am trying to rewrite the code with a few changes at my end, however I am stuck in understanding why my bindView is showing unresolved. I tried copying your entire gradle contents but still bindView is unresolved. Can you please help me in understanding whats the reason behind this.

**Comment by pcsaunak** [comment]
Found your implementation. Thanks. Closing this.

**Comment by nikhilpanju** [comment]
You can use [View Binding](https://developer.android.com/topic/libraries/view-binding) with Android Studio 3.6 and bypass this issue.
